### ISSUE TITLE
Personalize not intro

### ISSUE THREAD

**Issue by iamvery** [tech256/r2d8#13]
Chris Beaman said

> I think it might be great if r2d8 had a more personal introduction, ie. if it introduced the mods by name and maybe even by photo.

**Comment by PallasStreams** [comment]
While this sounds like a great idea, the welcome message already says a lot. I would think this would add too much text for the new person to read and might overwhelm them having just joined. Thoughts?

**Comment by PallasStreams** [comment]
Since we've gone almost 4 years without this coming up again I'm going to close it for now. @iamvery if you decide this is still needed feel free to reopen and assign to me and I'll take a look at it.
