### ISSUE TITLE
bot name is case sensitive

### ISSUE THREAD

**Issue by PallasStreams** [tech256/r2d8#35]
Using the command `thanks r2d8`, the bot does not respond. However, using `thanks R2D8` the bot responds with `At your service.` It appears that using the bot name is case sensitive. This should not be the case as we don't know how the user is going to type the name into chat.

Note: This applies to all commands not just the `thanks R2D8` command.

**Comment by ProfessorTom** [comment]
This was addressed with #40.

Please close.
