### ISSUE TITLE
Fix CircleCI build

### ISSUE THREAD

**Issue by PallasStreams** [tech256/r2d8#41]
We should update CircleCI so that it can run the new Jest unit tests and verify new PRs don't break existing functionality.

**Comment by ProfessorTom** [comment]
Funnily enough, I did notice that the build was failing,

I was able to get CircleCI to run on my repo and the tests passed. ( [Link}(https://circleci.com/gh/ProfessorTom/r2d8) )

I glanced at the logs for this repo earlier. I didn't understand why everything was failing.

**Comment by PallasStreams** [comment]
Note sure if it's related but when I go look at the project in Circle CI I see this
![image](https://user-images.githubusercontent.com/2483249/83088226-be63d000-a058-11ea-837e-c4347dc25c76.png)

**Comment by ProfessorTom** [comment]
Oh, fun!

**Comment by ProfessorTom** [comment]
Could someone create a `circleci-project-setup` branch so I can PR the change I have in my branch of the same name ands see if that file gets the tests building on that branch?

If that works, I'll look into taking the existing CircleCI file in this project and combining it with the file I have, noting, of course, that I don't have the keys to test deployment.

P. S. Does anyone know when the last r2d8 deployment was? cc @iamvery

**Comment by PallasStreams** [comment]
AFAIK there has never been a deployment of R2D8 from Circle CI.

**Comment by ProfessorTom** [comment]
@iamvery Can you do two things:

1. Remove and add this repo to Circle CI
2. Give @PallasStreams and myself admin privileges for CircleCI for this repo so we can make adjustments as necessary

**Comment by PallasStreams** [comment]
I believe the PR meant to tag #46 instead of this issue. Reopening until we are able to resolve.

**Comment by PallasStreams** [comment]
This was fixed by #56
