### ISSUE TITLE
@channel doesn't display the warning

### ISSUE THREAD

**Issue by ProfessorTom** [tech256/r2d8#46]
As a Tech256 user, when someone uses `@channel`, I want r2d8 to tell them to use `@here` instead.

## Reproduction steps
1. type and send a message in a channel that r2d8 is in that tacontains `@channel`

## Expected Behavior
r2d8 responds with a message telling the user to use `@here` instead.

## Actual Behavior
r2d8 does not response to the message at all.

**Comment by PallasStreams** [comment]
Fixed by #48
