### ISSUE TITLE
Add Karma support

### ISSUE THREAD

**Issue by PallasMedia** [tech256/r2d8#57]
# Summary
Users should be able to give and remove karma to other users. Users should also be able to give kamra to a specific phrase. If the phrase contains ++ or has spaces in it the phrase should be enclosed in double quotes. For example "C++"++ to avoid giving karma to C.

# Examples
rockets++ 
rockets--
jay++
jay--
"C++"++
"C++"--
"Object Oriented Programming"++
"Object Oriented Programming" --

**Comment by ProfessorTom** [comment]
I wonder if this should be an Epic and we have other issues that are each of the pieces.

Some things I see missing:
* `!karma help`
* `!karma stats`
* `!karma @username`
* `!karma word`
*  `!karma multiword phrase`

**Comment by PallasStreams** [comment]
They were missing because I couldn't remember what all we said when I wrote the issue.
