### ISSUE TITLE
Migrate source code to TypeScript

### ISSUE THREAD

**Issue by PallasMedia** [tech256/r2d8#58]
By having the code written in TypesScript we would have Intellisense in VS Code which will make it easier to debug problems as they happen.

**Comment by ProfessorTom** [comment]
There currently aren't typings for Slackbot, though there is an [issue](https://github.com/mishk0/slack-bot-api/issues/122).

I don't think we care about the bot itself as much as we care about the code we're writing on top of the bot.

It could be argued that we don't even care about the messaging code that we just completed.

But it would be a HUGE advantage when we start doing db stuff.

**Comment by PallasStreams** [comment]
What does Slackbot not having typings have to do with this issue? I was referring to our code.

**Comment by ProfessorTom** [comment]
I was really leaving a note to myself for later.

What I was trying to say is that since `slackbot` doesn't yet provide typings, it would be difficult–but not impossible–to convert the entire project to Typescript.

**Comment by PallasMedia** [comment]
Per past discussions this may not be feasible at this time so closing. If the bot library we use decides to add typings in the future we can reopen this and revisit the idea.
